### GET list user
GET http://localhost:3002/users


### CREATE user

POST http://localhost:3002/users/ 
content-type: application/json

{
    "name": "milo4",
    "email": "milo4@gmail.com"
}

### UPDATE user
PUT http://localhost:3002/users 
content-type: application/json

{
"email":"milo@gmail.com", 
"password": "12345"
}


### DELETE user
DELETE http://localhost:3002/users/1
content-type: application/json
